// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEDsJhIP4-QJ5NCamfIkoHVvQEgKo-kzU',
    appId: '1:676850899690:web:eb2f3b9132ec17baa3d593',
    messagingSenderId: '676850899690',
    projectId: 'yorozuya-app',
    authDomain: 'yorozuya-app.firebaseapp.com',
    storageBucket: 'yorozuya-app.firebasestorage.app',
    measurementId: 'G-C8G8SY19FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEJKlA25OWDgsGLYRa-VMpb7Im1gIrmM8',
    appId: '1:676850899690:android:9265dd772d248fcba3d593',
    messagingSenderId: '676850899690',
    projectId: 'yorozuya-app',
    storageBucket: 'yorozuya-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLCEgulpQflB23PgZRliQhLQgXhcuY6yU',
    appId: '1:676850899690:ios:16633fb2a8e8c5daa3d593',
    messagingSenderId: '676850899690',
    projectId: 'yorozuya-app',
    storageBucket: 'yorozuya-app.firebasestorage.app',
    iosBundleId: 'com.example.yorozuyaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLCEgulpQflB23PgZRliQhLQgXhcuY6yU',
    appId: '1:676850899690:ios:16633fb2a8e8c5daa3d593',
    messagingSenderId: '676850899690',
    projectId: 'yorozuya-app',
    storageBucket: 'yorozuya-app.firebasestorage.app',
    iosBundleId: 'com.example.yorozuyaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEDsJhIP4-QJ5NCamfIkoHVvQEgKo-kzU',
    appId: '1:676850899690:web:3807db5283f6f436a3d593',
    messagingSenderId: '676850899690',
    projectId: 'yorozuya-app',
    authDomain: 'yorozuya-app.firebaseapp.com',
    storageBucket: 'yorozuya-app.firebasestorage.app',
    measurementId: 'G-9CMTQ505CT',
  );
}
